ACMS-1240: Update Starter Kit to have toggle module feature
acquia/acquia_cms_common pull request #26
Opened 2022-06-14 14:39 UTC by chandan-singh7929

2022-06-14 14:42 UTC, chandan-singh7929 commented
@vishalkhode1 - I have not included following module as dependencies of common

- Acquia Connector
- Acquia Search
- Search API Solr

2022-06-20 19:44 UTC, fiasco requested changes

2022-06-21 11:33 UTC, chandan-singh7929 commented on acquia_cms_common.info.yml
> +  - drupal:honeypot
@fiasco - Thank you for input.
@vishalkhode1 - As discussed I am removing these module from ` .file` but we will keep this in `composer.json` and move these dependency in acquia_cms module/profile accordingly.

2022-06-21 11:33 UTC, chandan-singh7929 commented on acquia_cms_common.info.yml
> +  - drupal:recaptcha
Same for this one.

2022-06-23 06:51 UTC, chandan-singh7929 commented
@vishalkhode1 - As discussed, remove following modules dependencies from info file:
- drupal:google_analytics
- drupal:google_tag
- drupal:history
- drupal:honeypot
- drupal:recaptcha

2022-06-23 15:46 UTC, merged